[workspace]
resolver = "3"
members = ["cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
async-compat = "0.2.5"
async-signal = "0.2.13"
axum = "0.8.8"
base64 = "0.22.1"
chrono = { version = "0.4.43", features = ["serde"] }
clap = { version = "4.5.57", features = ["derive", "env"] }
frost-secp256k1 = { version = "2.2.0", features = ["serde"] }
futures = "0.3.31"
k256 = "0.13.4"
futures-rustls = { version = "0.26.0", default-features = false, features = [
    "ring",
] }
hmac = "0.12.1"
itertools = "0.14.0"
http-body-util = "0.1.3"
hyper = "1.8.1"
hyper-util = { version = "0.1.20", features = ["client", "http2"] }
num-bigint = "0.4.6"
num-traits = "0.2.19"
libp2p = { version = "0.56.0", features = [
    "autonat",
    "cbor",
    "dcutr",
    "gossipsub",
    "identify",
    "kad",
    "macros",
    "mdns",
    "noise",
    "ping",
    "quic",
    "relay",
    "request-response",
    "serde",
    "tokio",
    "upnp",
    "yamux",
] }
proc-macro2 = "1.0.106"
proptest = "1.9.0"
quote = "1.0.44"
rcgen = "0.14.7"
reqwest = { version = "0.13.1", features = ["json"] }
rustls = { version = "0.23.36", default-features = false, features = [
    "ring",
    "std",
    "tls12",
] }
sec1 = "0.7.3"
serde = { version = "1.0.228", features = ["derive"] }
sha3 = "0.10.8"
serde_json = "1.0.149"
smol = "2.0.2"
syn = { version = "2.0.114", features = ["full"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.6.8", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }
url = "2.5.8"
